services:

  backendapp:
    image: dockercomposebackend:2.0
    build:
      context: .
      dockerfile: DockerComposeDemoBackendApp/Dockerfile
    container_name: backendcontainer
    ports:
      - "5279:8080"

  uiapp:
    image: dockercomposeui:2.0
    build:
      context: .
      dockerfile: DockerComposeDemoUIApp/Dockerfile
    container_name: uicontainer
    ports:
      - "5129:8080"